logFile: /data/mywork/app/hometown/log/gin.log
mysqlLog: /data/mywork/app/hometown/log/mysql.log
httpPort: 80
webSocketPort: 6767
httpUrl: 9394.cool:80
webSocketUrl: 9394.cool:6379
imagePathIp: 9394.cool
imageSavePath: /data/mywork/app/hometown/images/
appSavePath: /data/mywork/app/hometown/apk/