#logFile: /data/mywork/app/hometown/log/gin.log
#mysqlLog: /data/mywork/app/hometown/log/mysql.log
#httpPort: 80
#webSocketPort: 6767
#httpUrl: 9394.cool:80
#webSocketUrl: 9394.cool:6379
#imagePathIp: 9394.cool
#imageSavePath: /data/mywork/app/hometown/images/
#appSavePath: /data/mywork/app/hometown/apk/
#mysqlPort: 3306
#mysqlPwd: 6678510Jk.
#mysqlDb: hometown

logFile: D:\GoWork\chat\gin.log
#mysqlLog: /data/mywork/app/hometown/log/mysql.log
httpPort: 8080
webSocketPort: 7979
httpUrl: 192.168.1.5:8080
webSocketUrl: 192.168.1.5:7979
imagePathIp: 192.168.1.5
imageSavePath: D:\GoWork\active_img\
mysqlPort: 3310
mysqlPwd: 123456
mysqlDb: hometown
appSavePath: D:\GoWork\active_img\apk\