version: "3"

services:
 app:
    links:
      - db
      - redis
    ports:
      - "8080:8080"
      - "7979:7979"
    volumes:
      - D:/GoWork/active_img:/dist/images/
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
 db:
    image: mysql:8.0
    volumes:
      - ./db/mysql_serve/init:/docker-entrypoint-initdb.d/
    ports:
      - "3310:3306"
    command: --default-authentication-plugin=mysql_native_password 
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    container_name: tmysql
    restart: on-failure
 redis:
    image: redis:6.0.5
    ports:
      - "6379:6379"
    container_name: tredis
    command:
      redis-server
    restart: on-failure

  
